#!/usr/bin/env bash
set -e

if [ -f config/task.env ]; then
  source config/task.env
fi

init () {
  mkdir -p target/resources
  if ! [ -d config ]; then
    cp -r config-TEMPLATE config
  fi
}

dev () {
  init
  source config/dev.env
  echo 7888 > .nrepl-port
  clj "$@" -A:dev -M -m findka.hallway.dev --port 7888 \
    --middleware '[cider.nrepl/cider-middleware]'
}

build () {
  rm -rf target
  init
  clj -A:dev -X findka.hallway.dev/build
}

deploy () {
  scp config/prod.env app@$TASK_HOST:config.env
  time git push prod master
}

logs () {
  ssh root@$TASK_HOST journalctl -u app -f -n 300
}

prod-repl () {
  echo Connect to nrepl port 7888
  ssh -NL 7888:localhost:7888 root@$TASK_HOST
}

"$@"
